#!/bin/bash

if [ "$1" == "clean" ]; then
	rm PizzaPartyDriver.class
	rm OurPizzaParty.class
	exit 0 
fi

javac -cp mariadb-java-client-2.2.3.jar: hw10.java
java -cp mariadb-java-client-2.2.3.jar: PizzaPartyDriver

#Arguments in bash scripting are passed as $1 $2 $3 and so on. 
